SET NOCOUNT ON;

PRINT '//==========================================='
PRINT '// Generated by SQL POCO-Generator script';
PRINT '// Date    : ' + CONVERT(CHAR(16), GETDATE(), 120);
PRINT '// Server  : ' + @@SERVERNAME;
PRINT '// Database: ' + DB_NAME();
PRINT '//==========================================='
PRINT ''

DECLARE @baseClass VARCHAR(200);
DECLARE @tableName VARCHAR(200);
DECLARE @columnName VARCHAR(200);
DECLARE @nullable VARCHAR(50);
DECLARE @datatype VARCHAR(50);
DECLARE @maxlen INT;

DECLARE @sType VARCHAR(50);
DECLARE @sProperty VARCHAR(200);

DECLARE @tTableExludes TABLE([Name] sysname NOT NULL);
DECLARE @tColumnExludes TABLE([Name] sysname NOT NULL);

SET @baseClass = 'BaseModel'; /* Set @baseClass if you want every class to inherit it, otherwise set to NULL */

INSERT INTO @tTableExludes ([Name])
VALUES 
	('sysdiagrams')

INSERT INTO @tColumnExludes ([Name])
VALUES 
	('id'),
	('created'),
	('updated')

DECLARE table_cursor CURSOR LOCAL READ_ONLY FORWARD_ONLY FOR
SELECT
	TABLE_NAME
FROM
	[INFORMATION_SCHEMA].[TABLES] T
WHERE
	NOT EXISTS(SELECT [Name] FROM @tTableExludes E WHERE E.Name = T.TABLE_NAME )

OPEN table_cursor;

FETCH NEXT FROM table_cursor
INTO
	@tableName;

WHILE @@FETCH_STATUS = 0
BEGIN

	PRINT 'public class ' + @tableName + IIF(@baseClass IS NULL, '', ' : ' + @baseClass) + ' {';

	DECLARE column_cursor CURSOR LOCAL READ_ONLY FORWARD_ONLY FOR
	SELECT
		COLUMN_NAME,
		IS_NULLABLE,
		DATA_TYPE,
		ISNULL(CHARACTER_MAXIMUM_LENGTH, '-1')
	FROM
		[INFORMATION_SCHEMA].[COLUMNS] C
	WHERE
		C.[TABLE_NAME] = @tableName
		AND NOT EXISTS(SELECT [Name] FROM @tColumnExludes E WHERE E.Name = C.COLUMN_NAME )
	ORDER BY
		[ORDINAL_POSITION];

	OPEN column_cursor;
	FETCH NEXT FROM column_cursor
	INTO
		@columnName,
		@nullable,
		@datatype,
		@maxlen;

	WHILE @@FETCH_STATUS = 0
	BEGIN

		-- datatype
		SELECT
			@sType = CASE @datatype
						 WHEN 'int' THEN
							 'Int32'
						 WHEN 'decimal' THEN
							 'Decimal'
						 WHEN 'money' THEN
							 'Decimal'
						 WHEN 'char' THEN
							 'String'
						 WHEN 'nchar' THEN
							 'String'
						 WHEN 'varchar' THEN
							 'String'
						 WHEN 'nvarchar' THEN
							 'String'
						 WHEN 'uniqueidentifier' THEN
							 'Guid'
						 WHEN 'datetime' THEN
							 'DateTime'
						 WHEN 'bit' THEN
							 'Boolean'
						 ELSE
							 'String'
					 END;

		IF (@nullable = 'NO')
			PRINT '[Required]';
		IF (@sType = 'String' AND @maxlen <> '-1')
			PRINT '[MaxLength(' + CONVERT(VARCHAR(4), @maxlen) + ')]';
		SELECT
			@sProperty = 'public ' + @sType + ' ' + @columnName + ' { get; set;}';
		PRINT @sProperty;

		PRINT '';
		FETCH NEXT FROM column_cursor
		INTO
			@columnName,
			@nullable,
			@datatype,
			@maxlen;
	END;
	CLOSE column_cursor;
	DEALLOCATE column_cursor;

	PRINT '}';
	PRINT '';
	FETCH NEXT FROM table_cursor
	INTO
		@tableName;
END;
CLOSE table_cursor;
DEALLOCATE table_cursor;
